[package]
name = "mini-blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.11.0-pre.4"
chrono = "0.4.39"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"